title:  Roy Berube
tagline:  meanderings

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/royberube'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/royberube/'}
- {icon: 'envelope', link: 'mailto:royberube1965@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
